### PR TITLE
! add japan language

### PR DESCRIPTION
**Pull request by padgithub**
plz merge pull request. I add Japanese language to your library.

### CODE REVIEW

**Comment by Boris-Em** [comment]
Thank you for your contribution @padgithub!
It looks like you have a merge conflict on the project file. 
Could you solve that?

**Comment by padgithub** [comment]
i fixed conflict, plz check it

**Review by AvdLee — APPROVED** [review]

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  **WeScanTests/CIRectangleDetectorTests.swift#L55** - **WeScanTests.CIRectangleDetectorTests: testCorrectlyDetectsAndReturnsQuadilateral**<br />failed - Snapshot comparison failed: Optional(Error Domain=FBSnapshotTestControllerErrorDomain Code=4 "Images different" UserInfo={NSLocalizedFailureReason=image pixels differed by more than 0.00% from the reference image, FBDiffedImageKey=<UIImage:0x6000016d7ba0 anonymous {300, 300}>, FBReferenceImageKey=<UIImage:0x6000016cad00 anonymous {300, 300}>, FBCapturedImageKey=<UIImage:0x6000016d4240 anonymous {150, 150}>, NSLocalizedDescription=Images different})
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  **WeScanTests/VisionRectangleDetectorTests.swift#L69** - **WeScanTests.VisionRectangleDetectorTests: testCorrectlyDetectsAndReturnsQuadilateral**<br />failed - Snapshot comparison failed: Optional(Error Domain=FBSnapshotTestControllerErrorDomain Code=4 "Images different" UserInfo={NSLocalizedFailureReason=image pixels differed by more than 0.00% from the reference image, FBDiffedImageKey=<UIImage:0x6000016cbf00 anonymous {150, 150}>, FBReferenceImageKey=<UIImage:0x6000016d15f0 anonymous {150, 150}>, FBCapturedImageKey=<UIImage:0x6000016cbb10 anonymous {150, 150}>, NSLocalizedDescription=Images different})
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the WeScanSampleProject editor. (in target 'WeScanSampleProject' from project 'WeScan')</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.1, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'FBSnapshotTestCase iOS' from project 'FBSnapshotTestCase')
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/2a741a671a8b9fa1" target="_blank">Bitrise</a>
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>WeScan: Executed 56 tests, with 2 failures (0 unexpected) in 24.902 (24.982) seconds</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 0d1b253de5762b2752e02c8886994a6d3b183ae9
</p>

**Comment by AvdLee** [comment]
@padgithub can you update your branch with the latest changes in master? It will fix CI 🙂

**Comment by padgithub** [comment]
Oki

Vào 17:41, Th 5, 21 thg 1, 2021 Antoine van der Lee <
notifications@github.com> đã viết:

**Comment by wetransferplatform** [comment]
Congratulations! :tada: This was released as part of [Release 1.8.1](https://github.com/WeTransfer/WeScan/releases/tag/1.8.1) :rocket:<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>

**Pull request merged**
