### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Review by BasThomas — APPROVED** [review]
🤩

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>BuildableError(message: "Some model objects have unexpectedly changed since the build was started. Please try again.", buildable: <IDESwiftPackageBundleProductBuildable:ObjectIdentifier(0x0000600002224150):'<invalidated>'>)</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Testing cancelled because the build failed.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>'gray' was deprecated in iOS 13.0: renamed to 'UIActivityIndicatorView.Style.medium'</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'blackTranslucent' was deprecated in iOS 13.0: Use UIBarStyleBlack and set the translucent property to YES instead.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'blackTranslucent' was deprecated in iOS 13.0: Use UIBarStyleBlack and set the translucent property to YES instead.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'isAutoStillImageStabilizationEnabled' was deprecated in iOS 13.0</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'jpegPhotoDataRepresentation(forJPEGSampleBuffer:previewPhotoSampleBuffer:)' was deprecated in iOS 11.0</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  'init(source:)' was deprecated in iOS 12.0: Core Image Kernel Language API deprecated. (Define CI_SILENCE_GL_DEPRECATION to silence these warnings)
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>Please provide a summary in the Pull Request description</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/46372985-4bf2-4c4d-90ae-a547a514cf4a" target="_blank">Bitrise</a>
  </td>
    </tr>
  </tbody>
</table>

## Code Coverage Report
| Name | Coverage ||
| --- | --- | --- |


### SwiftLint found issues

| Severity | File | Reason |
| -------- | ---- | ------ |
Warning | CaptureSessionManager.swift:259 | The disabled 'function_parameter_count' rule should be re-enabled before the end of the file (`blanket_disable_command`) |
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 8af804f0aa969a364193a557d24f58e9d0179741
</p>

**Review by AvdLee — APPROVED** [review]

**Comment by AvdLee** [comment]
Thanks a lot, these changes are always welcome! 🙌

**Comment by wetransferplatform** [comment]
Congratulations! :tada: This was released as part of [Release 3.0.0-beta.1](https://github.com/WeTransfer/WeScan/releases/tag/3.0.0-beta.1) :rocket:<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>

**Pull request merged**
