### PR TITLE
Append French localization and fix Xcode 10 compilation

### PR DESCRIPTION
**Pull request by florentmorin**
French localization was added to project. Based on similar processes from other apps.

And fixes were append when compiling project using CocoaPods under Xcode 10:
- `Info.plist` is now excluded from compilation
- Swift version is now set to `4.0` to avoid problem with Swift 4.2 compatibility.

### CODE REVIEW

**Comment by justJS** [comment]
Can you just keep the French localization for now? #41 has multiple changes to the project structure which should fix the other issues, if not, I think it’s better if you resend this PR later so we avoid merge conflicts.

**Comment by florentmorin** [comment]
OK. I will follow changes and create a new PR later, once #41 is merged to `master`.

**Comment by justJS** [comment]
👍

**Comment by pedrofspinho** [comment]
Will this be available soon?

**Comment by justJS** [comment]
It’s waiting for #41, but there’s no response from the owners of the project so far.

**Comment by AvdLee** [comment]
Just as a heads up, we're currently doing our best to walk through the PRs this week. #41 takes quite a while, so if we can merge this in already, that would be preferable. After that, #41 can pull in develop again to keep up with the latest changes.

I've added @Boris-Em as reviewer to approve this PR.

**Comment by justJS** [comment]
Localizations don't seem to be working as per #67, that's pretty important to be addressed before we add further localizations.

**Comment by AvdLee** [comment]
@florentmorin would you mind merging in develop to let CI do his job?

**Comment by florentmorin** [comment]
Yes. I will do that ASAP.

Florent Morin

**Comment by florentmorin** [comment]
@AvdLee Looks OK with #87

**Pull request closed without merging**
