### PR TITLE
Default value for rectangle detection in iOS 11.x and later

### PR DESCRIPTION
**Pull request by mikeperrett**
The default value for VNDetectRectanglesRequest::minimumAspectRatio is 0.5.
What this means is that any document less than a 1:2 ratio will fail.

This is related to an open issue:
https://github.com/WeTransfer/WeScan/issues/137#issue-415895775

Suggest we use a default value of at least 0.1
I see there is a feature request for passing various options.
https://github.com/WeTransfer/WeScan/issues/81#issue-380241097

Perhaps passing a minimumAspectRatio would suit the needs of more applications.

### CODE REVIEW

**Comment by justJS** [comment]
Could we use 0.3 for now since you said it works? I fear that using such a low number will negatively affect the rectangle detection for normal documents.

**Comment by mikeperrett** [comment]
Can do, 0.3 works for my 2.5x6 and 3x10 documents. 
I'll update my fork.
Ultimately it would be nice to see it configurable to suit more needs

**Comment by mikeperrett** [comment]
@Boris-Em @justJS 
Update succeeded, this can be merged with origin develop if there are no objections.

**Comment by AvdLee** [comment]
@mikeperrett looks good to me! If you have good ideas on making this configurable, feel free to drop a PR. We're happy to take a look and implement it with you!

**Comment by justJS** [comment]
^ Yep! Unfortunately I haven’t had much time to work on it but I think it’s still a WIP to add support for preferences so we can do this and custom colors and other stuff

**Comment by AvdLee** [comment]
@mikeperrett do you know whether your fork is completely up to date with the latest changes? CI seems to fail unexpectedly 🤔

**Comment by mikeperrett** [comment]
@AvdLee I just merged the latest, should be good to go momentarily

**Comment by mikeperrett** [comment]
@AvdLee The CI passed; this can be merged whenever is convenient

**Pull request merged**
