### PR TITLE
Change `class` to `AnyObject` for protocols

### PR DESCRIPTION
**Pull request by BasThomas**
This was emitting a warning.

### CODE REVIEW

**Review by AvdLee — APPROVED** [review]

**Comment by AvdLee** [comment]
CI failure is on our side. Thanks for your contribution!

**Comment by BasThomas** [comment]
Hm, seems related to installing Danger? I can check if updating dependencies helps?

**Comment by AvdLee** [comment]
> Hm, seems related to installing Danger? I can check if updating dependencies helps?

I'm pretty sure this is in our Bitrise configuration as we changed some things recently!

**Comment by AvdLee** [comment]
> Hm, seems related to installing Danger? I can check if updating dependencies helps?

But feel free to try :D

**Pull request merged**
