### PR TITLE
Update example GIF with new changes

### PR DESCRIPTION
**Pull request by justJS**
This pull request updates the GIF on the README with recent changes.

### CODE REVIEW

**Comment by justJS** [comment]
@AvdLee @Boris-Em It seems builds are continuously failing recently with Travis-CI:

```The Xcode build system has crashed. Please close and reopen your workspace.```

**Comment by AvdLee** [comment]
@justJS probably related to derived data. I fixed this on develop, let's see if that fixes the issue.

**Comment by justJS** [comment]
Looks good now! Thanks 🙂

**Comment by justJS** [comment]
🎉

**Pull request merged**
