### PR TITLE
Added Swedish language support

### PR DESCRIPTION
**Pull request by onlsn**
Added Swedish localization.

### CODE REVIEW

**Review by AvdLee — APPROVED** [review]

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  **WeScanTests/CIRectangleDetectorTests.swift#L55** - **WeScanTests.CIRectangleDetectorTests: testCorrectlyDetectsAndReturnsQuadilateral**<br />failed - Snapshot comparison failed: Optional(Error Domain=FBSnapshotTestControllerErrorDomain Code=4 "Images different" UserInfo={NSLocalizedFailureReason=image pixels differed by more than 0.00% from the reference image, FBDiffedImageKey=<UIImage:0x6000004ff570 anonymous {300, 300}>, FBReferenceImageKey=<UIImage:0x6000004e6520 anonymous {300, 300}>, FBCapturedImageKey=<UIImage:0x6000004e4c60 anonymous {150, 150}>, NSLocalizedDescription=Images different})
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  **WeScanTests/VisionRectangleDetectorTests.swift#L69** - **WeScanTests.VisionRectangleDetectorTests: testCorrectlyDetectsAndReturnsQuadilateral**<br />failed - Snapshot comparison failed: Optional(Error Domain=FBSnapshotTestControllerErrorDomain Code=4 "Images different" UserInfo={NSLocalizedFailureReason=image pixels differed by more than 0.00% from the reference image, FBDiffedImageKey=<UIImage:0x6000004e1830 anonymous {150, 150}>, FBReferenceImageKey=<UIImage:0x6000004e5560 anonymous {150, 150}>, FBCapturedImageKey=<UIImage:0x6000004e17a0 anonymous {150, 150}>, NSLocalizedDescription=Images different})
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.1, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target 'FBSnapshotTestCase iOS' from project 'FBSnapshotTestCase')
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the WeScanSampleProject editor. (in target 'WeScanSampleProject' from project 'WeScan')</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/b8550f9bbe396990" target="_blank">Bitrise</a>
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>WeScan: Executed 56 tests, with 2 failures (0 unexpected) in 22.512 (22.608) seconds</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against bc209da4a86497bfacdd6391872d7b556316f305
</p>

**Comment by onlsn** [comment]
.

**Comment by AvdLee** [comment]
@onlsn can you merge in develop? It will fix CI 🙂

**Comment by onlsn** [comment]
> with the latest changes in master
@AvdLee this should now be done!

**Pull request merged**
