### PR TITLE
Batch scanning, Swift 4.2, Dark Mode

### PR DESCRIPTION
**Pull request by technology08**
Hi guys! Thanks for the awesome repository, helping me tremendously with my app. I needed batch scanning, retheming, and the corner views fixed, and I wanted to share this with the rest of you. This PR includes:

- Swift 4.2 conversion
- Corner Views fixed (ZoomGestureController removed)
- Batch scanning with [ImageScannerResults]
- add.png from material.io website for icon
- All black retheme 

Please let me know any questions you have or things you want me to change.

### CODE REVIEW

**Comment by technology08** [comment]
This does work in both the sample project and my own app.

**Comment by justJS** [comment]
Thanks for your PR! 

However, I feel like this changes major parts of WeScan and causes *breaking* changes for many apps which use it.

Here are a few points:
- **An array of results is now returned, forcing breaking changes on apps which may automatically update without input from the developers**
- Add icon is Material Design, when WeScan tries to fit in with iOS
- Add icon is not in the asset catalog, and 2x/3x versions aren't provided
- Dark mode is a strong change, and is not an option
- This PR removes strangely completely removes support for localizations
- This PR comments out a lot of code rather than removing it if unnecessary 
- This PR contains multiple separate changes, such as a Swift migration, a theme, and batch scanning

Based on this, I'd be in favor of splitting this PR into separate PR's, and each of them being evaluated separately. Additionally, I'd prefer having options for both batch scanning and dark mode from the host app, as some apps may not want to support batch scanning.

(Note: This PR should also wait for #41 as it would have to be reimplemented)

**Comment by technology08** [comment]
Absolutely! This is my first PR, more hoping you would adapt them to fit in a bigger picture. Thanks for your quick reply, and yes, I can break batch scanning into its own PR where it is an option for apps to implement. Thanks for your feedback!

**Comment by justJS** [comment]
No problem - not trying to say this PR is bad or anything, just that it could be separated and made clearer :)

Also, something I forgot to mention: iOS has a built in Add icon for bar buttons, we could use the default one instead of a custom one?

**Comment by technology08** [comment]
How would you access the iOS icon outside of a UIBarButtonItem

**Comment by justJS** [comment]
I don't think you can. I haven't been able to test out the example app yet, is the add icon not being used in a bar button?

**Comment by justJS** [comment]
Ah just checked it out. It seems quite unfriendly for iOS. How about having the add icon next to the Done button?

**Comment by technology08** [comment]
No, as a normal UIButton with constraints.

**Comment by technology08** [comment]
Hm... that's an interesting idea. Yeah, that works and saves a ton of constraint problems :)

**Comment by justJS** [comment]
Also, can you check out #41? It contains a revamp of the scanning screen and multiple scanning changes, which is why I think we should wait till that gets merged (should be soon, waiting to hear back from @Boris-Em)

**Comment by technology08** [comment]
Yes, sure! Currently downgrading from Swift 4.2 to Swift 4.0. I'm going to come back to this tomorrow, still a student and have to finish some homework for tomorrow. Thanks for all of your feedback! Like I said, I'm new to the open source community, and I plan to contribute more in the future.

**Comment by justJS** [comment]
No problem - I'm a student too. We have quite a lot in common 😉

**Comment by Boris-Em** [comment]
Thank you so much for this PR @technology08! Great work.
As @justJS said, it would make it much easier for us if you could break down this PR into multiple smaller ones.
The other points made by @justJS are also valid. For example, dark mode should be optional, and not the default mode.
I'm closing this PR and hope that you will open new ones :)

**Pull request closed without merging**
