### PR TITLE
switch to CIPhotoEffectMono filter for grey scaling

### PR DESCRIPTION
**Pull request by JulianKahnert**
Hi,
first of all: thank you very very much for open sourcing this project! I am working on an iOS version of [PDF Archiver](https://pdf-archiver.io) and want to use WeScan for scanning the documents, which will be saved as PDFs (via [SwiftyTesseract](https://github.com/SwiftyTesseract/SwiftyTesseract)).

I started scanning some documents and got some bad results for the "enhanced picture" in the review screen:

I changed the "adaptive threshold" filter to  "[CIPhotoEffectMono](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CIPhotoEffectMono)" (in https://github.com/PDF-Archiver/WeScan/commit/4b183522cc5d5d229cc545a8bf3bb06d98cc3839) which improved the results:

Since this is no large testbase I am not sure, if this decreases the image quality in some cases. Some more information about the images:
- They come from 2 different "scan sessions".
- The images are screenshots of the "ReviewViewController". 

What do you think about it?

### CODE REVIEW

**Comment by justJS** [comment]
Hey @JulianKahnert, thanks for your pull request! However, your enhancement results are the expected result, the enhance feature works best only on white documents. `CIPhotoEffectMono` merely makes it grayscale, which is not the point of the enhance button.

**Comment by JulianKahnert** [comment]
Hi @justJS, oh that was quick. Thanks for your answere. Maybe the pictures above are bad examples, so I first made a picture of my "scan-setup":


As you can see, I've got a light on the right side of my desk, which has the following impact on the scanned picture:


If the `CIPhotoEffectMono` filter is used, it will result in this:


In this situation the "enhance" feature clearly fails and in my opinion a grayscale is a good choice for this. But it's absolutely fine, if you want to reject this pull request because you have some other use cases in mind.

**Comment by jcampbell05** [comment]
This there a flatten core image filter ? This feels like we need to eliminate the gradients from the image. 

Ultimately we may need to look into a machine learning model to handle the best filter for this

**Comment by AvdLee** [comment]
It seems that this addition could be very valuable, looking at the examples @JulianKahnert is giving. Can we make this a separated enhancing feature with a new button for example? This makes it possible to decide for the users themselves which one to chose.

However, ideally, we would make this decision automatically for the user. Is there any way we can detect that this new way of filtering is a better fit for a certainly taken picture?

**Comment by jcampbell05** [comment]
@AvdLee In my opinion we would implement some sort of algorithm whether thats a simple computer vision algorithm or machine learning.

It computes the gradient of the image (i.e the direction of the change of shade of the document), if it detects a strong gradient in the image it will try to adjust the image to flatten it.

Once its done that the standard enhancement method should work. 

I also know dropbox have done some work on this so will be interesting to see how they solved it but I think they went ML route.

**Comment by AvdLee** [comment]
> @AvdLee In my opinion we would implement some sort of algorithm whether thats a simple computer vision algorithm or machine learning.
> 
> It computes the gradient of the image (i.e the direction of the change of shade of the document), if it detects a strong gradient in the image it will try to adjust the image to flatten it.
> 
> Once its done that the standard enhancement method should work.
> 
> I also know dropbox have done some work on this so will be interesting to see how they solved it but I think they went ML route.

The intention of this framework is to keep it simple. We would we open for such implementation, but adding extra frameworks for example would not be our ideal route. Feel free to get this started and see what is possible though!

**Comment by jcampbell05** [comment]
> The intention of this framework is to keep it simple. We would we open for such implementation, but adding extra frameworks for example would not be our ideal route. Feel free to get this started and see what is possible though!

Of course but this should be possible with the built in apple frameworks :)

**Comment by JulianKahnert** [comment]
Hi @justJS, @jcampbell05 and @AvdLee,

It is very nice to see this discussion 🙂 just out of curiosity:
What is your definition of “enhancement”? Are those images enhanced in terms of disk space ... readability ... ?

My [use case](https://pdf-archiver.io/) is the long term archiving of all kind of personal documents. In this case it doesn’t matter if the image/pdf has a size of e.g. 3MB. On the other hand, I do not need any color information in the picture, since most of the documents contain some sort of text.
Since I do not want to lose content information in the picture, in my opinion the greyscale is quite a good compromise between large images and the possibility of loosing content information.

**Comment by jcampbell05** [comment]
@julik So enhancement in this case is trying to make the image represent the document as closely as possible. So for example removing any artifacts that are a result of the scan being a photo of the document, so that it represents what the original digital copy of the document would have looked like (Think of Star Wars the Enhanced Edition :) )

So the filter we've used before worked in many simple black and white documents as it could bring out the blacks and whites removing any environmental light hitting the page. However in some cases like yours where there is a strong light source it causes it to create a really hard gradient.

So we can potentially make this a flag to allow the developer choose which filter suits their use case but in the long run some sort of way to detect which filter is the best or just to create an algo that can cope in more conditions (similar to how dropbox did with Machine Learning)

**Comment by JulianKahnert** [comment]
@jcampbell05 thanks for your explanation! 🙂 I like the idea of adding a flag for this filter. What to you think @AvdLee and @justJS?

**Comment by AvdLee** [comment]
@JulianKahnert absolutely, for a first version, a flag is great! We can then start iterating and see whether we can automatically detect whether the filter is better or maybe add a UI option for this later.

**Comment by AvdLee** [comment]
@JulianKahnert can you update us on the status for this PR? Did you find time to add the flag?

**Comment by JulianKahnert** [comment]
@AvdLee sry for the late reply! I added the flag. What do you think about this solution? Would you prefer in enum in case you add even more enhancement methods?

**Comment by JulianKahnert** [comment]
@AvdLee to be honest, I am not very happy with the current "flag-solution". This flag has to be forwarded to multiple controllers (from the `ImageScannerController` to the `EditScanViewController` *and* `ScannerViewController`). This does not feel right to me...what do you think? Furthermore since iOS 13 will add this feature in the SDK (#170) could be replaced and must not be maintained, right?

**Comment by AvdLee** [comment]
@JulianKahnert we were not aware of that, that's great! Are you OK with me closing this one then so we can reopen a new PR for an iOS 13 implementation?

**Comment by JulianKahnert** [comment]
Hey @AvdLee that’s totally fine! 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
