### PR TITLE
Removes not needed guard

### PR DESCRIPTION
**Pull request by valeriyvan**
max func works consistently on a sequence of any length.

From documentation:

Returns
The sequence’s maximum element if the sequence is not empty; otherwise, nil.

### CODE REVIEW

**Comment by justJS** [comment]
Wouldn’t removing the guard make it return nil if there’s only one Quad instead of the current behavior of returning the only Quad?

**Comment by justJS** [comment]
Thanks for the addition of the test, but what I meant by my previous comment is this:

On the old implementation, if you had *2 or more* rectangles, it would have returned the bigger one. If you had *1* rectangle, it would return the only rectangle.

On the new implementation, as per the documentation (`The sequence’s maximum element if the sequence is not empty; otherwise, nil.`), if you have only *1* rectangle, it will now return `nil` rather than the only rectangle.

This is also demonstrated by the `testCorrectlyDetectsAndReturnsQuadilateral` test failing.

**Comment by valeriyvan** [comment]
No, documentation is correct! 
It says max return nil only for empty sequence, otherwise it returns maximum element. Single element sequence is not empty. For single element sequence that single element is max element (and min element as well). That how max/min work. 
But if documentation might me misunderstood that the reason improve it, I guess.

**Comment by valeriyvan** [comment]
Sure

**Comment by justJS** [comment]
I’ve reviewed the CI error and it seems there was some kind of issue with the snapshot tests. If you’ve try run them locally maybe you can see what the issue is clearer. (In your project folder just run “git submodules init; git submodules update” to install the library used for the tests)

**Comment by justJS** [comment]
Hey @valeriyvan, while I understand you are trying to fix the tests, `agnosticOptions` is only on the CIRectangleDetector tests because it was updated between iOS versions - so this has to stay there or the tests will fail. 

Also, I think it would be better to create a new PR for this, especially as it seems these are improvements to the tests rather than fixes (as the tests pass on all other PRs).

Hope that helps 🙂

**Comment by valeriyvan** [comment]
All tests passing locally. On the server one of snapshot tests fails with failure of loading reference image. FBSnapshotTestCase looks for reference image in ReferenceImages_32 when it is in ReferenceImages_64. According to documentation it should look both before failing.
Anyway, failing tests have nothing in common with the reason of this PR.

**Comment by valeriyvan** [comment]
Guys, @AvdLee requests fixing tests, @justJS requests fix tests in separate PR. Can't satisfy both of you.

**Comment by valeriyvan** [comment]
Anyway, I can't fix failing test at the moment. Snapshot test still looks for reference image in wrong directory.

**Comment by valeriyvan** [comment]
The reason of tests failing is not related to this PR.

**Comment by justJS** [comment]
I don't want to be hostile/create an argument here, but recently merged PRs did not have this issue, so it does seem to be an issue with this PR: #104 and #102 (both made by you) did not have this issue.

**Comment by valeriyvan** [comment]
I don't see this PR as breaking change. It was innocent change in its own.
After doesn't mean because of.
My be I am wrong and missing something.
One of reason of tests failed was crash because of force unwrap of nil in test itself. This was fixed by fixing test itself. It wasn't related to PR.
Second reason - snapshot test case looking wrong dir for reference image. Not related to PR as well. It was fixed by fixing tests as well.
All tests are passing locally. I have no idea why snapshot test case is still looking wrong dir at server.

**Comment by AvdLee** [comment]
Just to make sure, did you merge in the latest changes from develop into your branch? If so, it's our responsibility to fix CI and make it work again.

**Comment by valeriyvan** [comment]
Can't believe my eyes.

**Comment by valeriyvan** [comment]
Merge of develop haven't resolved issue with broken tests.
Accidentally switching Simulator from iPhone X to iPhone 7 and running tests I have found that tests started to fail locally. Update of reference images fixed broken tests. Now tests pass on only locally bon on CI as well.

**Comment by justJS** [comment]
Yes, because you changed the settings for the tests so the old reference images were outdated.

**Comment by valeriyvan** [comment]
Any reason why this isn't being merged?

**Comment by Boris-Em** [comment]
Waiting on @justJS's approval.

**Comment by AvdLee** [comment]
@justJS as long as our tests are succeeding, this shouldn't be a problem. Do you agree?

**Comment by justJS** [comment]
Fair enough, I’m ok with that. Let’s make sure to keep this in mind in case was have future issues with the tests 👍

**Pull request merged**
