### PR TITLE
feat: added Arabic language support

### PR DESCRIPTION
**Pull request by mohammadhamdan1991**
I've added the support for Arabic language

### CODE REVIEW

**Review by AvdLee — APPROVED** [review]
Thanks, this looks good!

**Comment by mohammadhamdan1991** [comment]
@AvdLee thank you very much for your approval,

**Review by Boris-Em — APPROVED** [review]
Thanks for your work @mohammadhamdan1991!

**Comment by wetransferplatform** [comment]
Congratulations! :tada: This was released as part of [Release 1.8.0](https://github.com/WeTransfer/WeScan/releases/tag/1.8.0) :rocket:<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>

**Pull request merged**
