### PR TITLE
Reintegrate WeScan package to Example app to make Xcode show package dependency normally

### PR DESCRIPTION
**Pull request by valeriyvan**
It's followup of PR #358.

This PR adds WeScan as dependency as local package.

Here's how project looks in Xcode now. Dependency is on the bottom of project navigator in section Package Dependencies. How it should be.

Screenshot 2023-06-21 at 23 55 56

Here's is how project looked before. WeScan package doesn't appear in Package Dependencies section. Instead it shows up before files of project itself.

246836157-e05e3f5e-bf7d-4ea5-9ef3-0ad318c90b02

### CODE REVIEW

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  **CIRectangleDetectorTests.testCorrectlyDetectsAndReturnsQuadilateral():**<br/>failed - Snapshot does not match reference.

@−
"/Users/vagrant/git/Tests/WeScanTests/__Snapshots__/CIRectangleDetectorTests/testCorrectlyDetectsAndReturnsQuadilateral.1.png"
@+
"/Users/vagrant/Library/Developer/CoreSimulator/Devices/D7CA41A8-547E-4DC0-9C53-FF5A41928CA5/data/tmp/CIRectangleDetectorTests/testCorrectlyDetectsAndReturnsQuadilateral.1.png"

To configure output for a custom diff tool, like Kaleidoscope:

    SnapshotTesting.diffTool = "ksdiff"

Actual perceptual precision 0.69906247 is less than required 0.97
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  **VisionRectangleDetectorTests.testCorrectlyDetectsAndReturnsQuadilateral():**<br/>failed - Snapshot does not match reference.

@−
"/Users/vagrant/git/Tests/WeScanTests/__Snapshots__/VisionRectangleDetectorTests/testCorrectlyDetectsAndReturnsQuadilateral.1.png"
@+
"/Users/vagrant/Library/Developer/CoreSimulator/Devices/D7CA41A8-547E-4DC0-9C53-FF5A41928CA5/data/tmp/VisionRectangleDetectorTests/testCorrectlyDetectsAndReturnsQuadilateral.1.png"

To configure output for a custom diff tool, like Kaleidoscope:

    SnapshotTesting.diffTool = "ksdiff"

Newly-taken snapshot does not match reference.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>'gray' was deprecated in iOS 13.0: renamed to 'UIActivityIndicatorView.Style.medium'</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'blackTranslucent' was deprecated in iOS 13.0: Use UIBarStyleBlack and set the translucent property to YES instead.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'blackTranslucent' was deprecated in iOS 13.0: Use UIBarStyleBlack and set the translucent property to YES instead.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'isAutoStillImageStabilizationEnabled' was deprecated in iOS 13.0</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'jpegPhotoDataRepresentation(forJPEGSampleBuffer:previewPhotoSampleBuffer:)' was deprecated in iOS 11.0</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  'init(source:)' was deprecated in iOS 12.0: Core Image Kernel Language API deprecated. (Define CI_SILENCE_GL_DEPRECATION to silence these warnings)
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>WeScanTests: Executed 60 tests (2 failed, 0 retried, 0 skipped) in 12.786 seconds</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Slowest test: RectangleFeaturesFunnelTests/testAddAlternateImage() (4.223s)</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Slowest test: RectangleFeaturesFunnelTests/testAddPreviouslyDisplayedRect() (3.094s)</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Slowest test: RectangleFeaturesFunnelTests/testAddMinUnderThreshold() (3.017s)</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/327a39e8-6ec8-4bed-a283-b3a56df52698" target="_blank">Bitrise</a>
  </td>
    </tr>
  </tbody>
</table>

## Code Coverage Report
| Name | Coverage ||
| --- | --- | --- |
WeScan | 37.76% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 28425358af41e068fb2d4ffb3e95e867a1c6e002
</p>

**Comment by BasThomas** [comment]
@AvdLee closed the previous pull request as a won't do, as per [this comment](https://github.com/WeTransfer/WeScan/pull/358#issuecomment-1600741664). Did you intend to open a new pull request?

**Comment by BasThomas** [comment]
Ah, I see it's added as a local package now. I'll leave this up to @AvdLee, as I'm not particularly familiar with local packages.

**Comment by AvdLee** [comment]
@valeriyvan This looks better, but I wonder whether editing still works. Does Xcode see this as a local package? In other words: are you able to alter the WeScan code from with the example project?

**Pull request closed without merging**
