### PR TITLE
fix resetMatchingScores

### PR DESCRIPTION
**Pull request by lengocgiang**
correct value matchingScore to 0

### CODE REVIEW

**Review by BasThomas — COMMENTED** [review]
Nice catch! Can we add a test for [the `add` function](https://github.com/WeTransfer/WeScan/blob/db24747dbd20f7fe649fce2ad877d8bc05559195/Sources/WeScan/Scan/RectangleFeaturesFunnel.swift#L100) that demonstrates this bugfix?

**Comment by lengocgiang** [comment]
@BasThomas : would you suggest how I might write unit tests for this fix? I'd like to contribute by adding unit tests if possible.

**Comment by BasThomas** [comment]
Good question, @lengocgiang. It's a bit tricky, given that `resetMatchingScores` is private, and so is `updateRectangleMatches` as well as the underlying `rectangles`.

Given that the `add` function on top of that does not always call its completion block... perhaps it's not worth adding a test for it at this point.

**Review by BasThomas — APPROVED** [review]

**Comment by lengocgiang** [comment]
@BasThomas thank you for your comment. If you have any requirements, please feel free to notice me. I will be happy to assist in any way I can.

**Comment by AvdLee** [comment]
@lengocgiang thanks for your contribution!

Our repository requires signed commits. Would it be possible for you to enable signed commits and recommit using the following command:

```
 git rebase --exec 'git commit --amend --no-edit -n -S' master
  git push --force
  ```
  
  You can read more about setting up signed commits [here](https://withblue.ink/2020/05/17/how-and-why-to-sign-git-commits.html).

**Comment by lengocgiang** [comment]
@AvdLee I have signed my commit as instructed. Could you please double-check it for me? Thank you!

**Comment by AvdLee** [comment]
CI failed due to Danger (solving that separately), but tests succeeded:

> [07:56:58]: ▸ Tests Passed: 0 failed, 0 skipped, 56 total (20.545 seconds)

Merging in, thanks for your contribution @lengocgiang 🎉

**Comment by lengocgiang** [comment]
@BasThomas @AvdLee thank you so much 🙏

**Pull request merged**
