### PR TITLE
Swift 4.2, Podspec file

### PR DESCRIPTION
**Pull request by monRo**
Was updated to swift 4.2
Fixed podspec file, It produced a duplication of the plist file

### CODE REVIEW

**Comment by justJS** [comment]
Dupe of #64. Please check existing PRs before creating a new one 😃

**Comment by monRo** [comment]
thx didn't see =)

**Comment by justJS** [comment]
No problem.

**Comment by justJS** [comment]
Hey, the close button is gone in #41. Maybe close this as it's a duplicate of #64? @monRo

**Pull request closed without merging**
