### PR TITLE
Omit default parameters in README examples

### PR DESCRIPTION
**Pull request by BasThomas**

### CODE REVIEW

**Comment by justJS** [comment]
I think it's best to leave those there so that new developers know they can use those parameters.

**Comment by BasThomas** [comment]
Wouldn't it be better to in that case show what the completionHandler does?
Something like `completion: { // do something after the view has been dismissed })`

**Comment by justJS** [comment]
Yeah, I think that would be a good idea

**Comment by Boris-Em** [comment]
Thanks for your contribution @BasThomas!

**Pull request merged**
