### PR TITLE
Clean up rectangle detectors

### LINKED ISSUE #112: Shouldn't completion be called here?
https://github.com/WeTransfer/WeScan/blob/3ef8b8e49687fead61be62914d53fee61be3b1d8/WeScan/Common/VisionRectangleDetector.swift#L39

### PR DESCRIPTION
**Pull request by justJS**
This cleans up the `CIRectangleDetector` and `VisionRectangleDetector` code as well as calls a missing completion where we should have been (as noted in #112).

Closes #112

### CODE REVIEW

**Comment by justJS** [comment]
So sorry - looks like I missed #115! We can wait for that to be merged, than after that merge this with the other improvements.

**Comment by justJS** [comment]
Resolved merge conflict due to merge of #115 (which means this PR is now fairly small but still clarifies a few things)

**Comment by justJS** [comment]
Updated PR by merging develop.

**Comment by AvdLee** [comment]
@justJS can you take a look at the merge conflict? @Boris-Em can you review the code?

**Comment by justJS** [comment]
@AvdLee fixed!

**Pull request merged**
