### PR TITLE
Remove deprecated properties

### PR DESCRIPTION
**Pull request by valeriyvan**
This solves issue #359 and #354

### CODE REVIEW

**Comment by wetransferplatform** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  **CIRectangleDetectorTests.testCorrectlyDetectsAndReturnsQuadilateral():**<br/>failed - Snapshot does not match reference.

@−
"/Users/vagrant/git/Tests/WeScanTests/__Snapshots__/CIRectangleDetectorTests/testCorrectlyDetectsAndReturnsQuadilateral.1.png"
@+
"/Users/vagrant/Library/Developer/CoreSimulator/Devices/D7CA41A8-547E-4DC0-9C53-FF5A41928CA5/data/tmp/CIRectangleDetectorTests/testCorrectlyDetectsAndReturnsQuadilateral.1.png"

To configure output for a custom diff tool, like Kaleidoscope:

    SnapshotTesting.diffTool = "ksdiff"

Actual perceptual precision 0.69906247 is less than required 0.97
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  **VisionRectangleDetectorTests.testCorrectlyDetectsAndReturnsQuadilateral():**<br/>failed - Snapshot does not match reference.

@−
"/Users/vagrant/git/Tests/WeScanTests/__Snapshots__/VisionRectangleDetectorTests/testCorrectlyDetectsAndReturnsQuadilateral.1.png"
@+
"/Users/vagrant/Library/Developer/CoreSimulator/Devices/D7CA41A8-547E-4DC0-9C53-FF5A41928CA5/data/tmp/VisionRectangleDetectorTests/testCorrectlyDetectsAndReturnsQuadilateral.1.png"

To configure output for a custom diff tool, like Kaleidoscope:

    SnapshotTesting.diffTool = "ksdiff"

Newly-taken snapshot does not match reference.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>'gray' was deprecated in iOS 13.0: renamed to 'UIActivityIndicatorView.Style.medium'</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  'init(source:)' was deprecated in iOS 12.0: Core Image Kernel Language API deprecated. (Define CI_SILENCE_GL_DEPRECATION to silence these warnings)
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'blackTranslucent' was deprecated in iOS 13.0: Use UIBarStyleBlack and set the translucent property to YES instead.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'blackTranslucent' was deprecated in iOS 13.0: Use UIBarStyleBlack and set the translucent property to YES instead.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'isAutoStillImageStabilizationEnabled' was deprecated in iOS 13.0</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>'jpegPhotoDataRepresentation(forJPEGSampleBuffer:previewPhotoSampleBuffer:)' was deprecated in iOS 11.0</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>WeScanTests: Executed 60 tests (2 failed, 0 retried, 0 skipped) in 13.505 seconds</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Slowest test: RectangleFeaturesFunnelTests/testAddAlternateImage() (4.483s)</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Slowest test: RectangleFeaturesFunnelTests/testAddPreviouslyDisplayedRect() (3.088s)</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Slowest test: RectangleFeaturesFunnelTests/testAddMinUnderThreshold() (3.013s)</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/884c1230-038a-4fdf-99f7-f32b508238c6" target="_blank">Bitrise</a>
  </td>
    </tr>
  </tbody>
</table>

## Code Coverage Report
| Name | Coverage ||
| --- | --- | --- |
WeScan | 37.76% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 1b3bafaff18164ca8b06f6f3e937b890507b67f5
</p>

**Review by AvdLee — APPROVED** [review]
Awesome!

**Comment by BasThomas** [comment]
FYI @AvdLee that I suggested to remove these rather than deprecating them, given that they have been obsolete in a previous version. https://github.com/WeTransfer/WeScan/issues/359#issuecomment-1598434860

**Review by BasThomas — APPROVED** [review]

**Comment by wetransferplatform** [comment]
Congratulations! :tada: This was released as part of [Release 3.0.0-beta.1](https://github.com/WeTransfer/WeScan/releases/tag/3.0.0-beta.1) :rocket:<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>

**Pull request merged**
